# Generated by Django 5.1.1 on 2024-11-14 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkillExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadlineInDays', models.IntegerField()),
                ('requiresEvidence', models.BooleanField()),
                ('done', models.BooleanField(default=False)),
                ('evidenceFile', models.FileField(blank=True, null=True, upload_to='evidence_files/')),
                ('awaiting_approval', models.BooleanField(default=False)),
                ('approval_requested', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('requiredPosition', models.CharField(max_length=200)),
                ('daysDuration', models.IntegerField(null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('version', models.IntegerField(default=1)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcomplexity')),
                ('skillExpertises', models.ManyToManyField(to='projects.projectskillexpertise')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('requiredPosition', models.CharField(max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('daysDuration', models.IntegerField(null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('OVERDUE', 'Overdue'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('not_rejected', 'Not rejected'), ('pending', 'Pending')], default='pending', max_length=25)),
                ('rejectionReason', models.CharField(choices=[('profile_rejected', 'Rejected due to profile'), ('deliverables_rejected', 'Rejected due to deliverables'), ('not_rejected', 'Not rejected'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('is_send', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finishJob', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(default=False)),
                ('complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcomplexity')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='accounts.freelancer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectContributor', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='projectContributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.projectcontributor'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='projects.project')),
                ('project_contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.projectcontributor')),
            ],
        ),
    ]
