# Generated by Django 5.1.1 on 2024-11-14 15:14

from django.db import migrations

def load_initial_project_data(apps, schema_editor):
    ProjectComplexity = apps.get_model('projects', 'ProjectComplexity')
    ProjectSkillExpertise = apps.get_model('projects', 'ProjectSkillExpertise')
    
    # Agregar niveles de complejidad
    complexities = [
        {'levelName': 'Basic', 'description': 'Suitable for beginners or entry-level projects.'},
        {'levelName': 'Intermediate', 'description': 'Requires moderate experience and skills.'},
        {'levelName': 'Advanced', 'description': 'Challenging projects for experienced professionals.'},
    ]
    
    for complexity in complexities:
        ProjectComplexity.objects.get_or_create(levelName=complexity['levelName'], defaults={'description': complexity['description']})
    
    # Agregar habilidades técnicas (skills)
    skills = [
        'Django', 'Python', 'Java', 'C++', 'JavaScript', 'HTML', 'CSS', 
        'React', 'Node.js', 'Express.js', 'SQL', 'PostgreSQL', 'MySQL', 
        'MongoDB', 'AWS', 'Azure', 'Google Cloud', 'Data Science', 'Machine Learning', 
        'NLP', 'Data Visualization', 'Cybersecurity', 'Encryption', 'Docker', 
        'Kubernetes', 'Microservices', 'DevOps', 'Software Testing', 'Automation Testing',
        'Network Security', 'Frontend Development', 'Backend Development', 'API Development'
    ]

    for skill in skills:
        ProjectSkillExpertise.objects.get_or_create(name=skill)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_project_data),
    ]
