# Generated by Django 5.1.1 on 2024-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='deadlineInDays',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='daysDuration',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
