# Generated by Django 5.1.1 on 2024-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='taxId',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='identification',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
