# Generated by Django 5.1.1 on 2024-11-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_address_alter_client_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description_company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
